[package]
authors = ["殷啟聰 | Kai-Chung Yan <seamlik@debian.org>"]
description = "Peer-to-peer chatting app hiding inside popular distributed networks"
edition = "2018"
name = "viska"
version = "0.0.1"

[package.metadata.riko]
targets = ["jni"]

[dependencies]
blake3 = { version = "0.3", features = ["pure"] }
futures = "0.3"
http = "0"
log = "0"
mime = "0"
quinn = "0.6.1"
rcgen = "=0.8.0" # Bug generating bad DER format
riko = { git = "https://github.com/seamlik/riko" }
riko_runtime = { git = "https://github.com/seamlik/riko" }
rustls = { version = "0", features = ["dangerous_configuration", "quic"]}
serde = { version = "1", features = ["derive"] }
serde_bytes = "0"
serde_cbor = "0"
serde_with = "1"
thiserror = "1"
tokio = { version = "0", features = ["full"] }
uuid = { version = "0", features = ["v4"] }
webpki = "0"

[dev-dependencies]
anyhow = "1"
clap = "2"
env_logger = "0"
structopt = "0"